
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/lzw1?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: lzw
      password: 1234
   jpa:

      generate-ddl: true
      properties:

         hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
   

   redis:

      host: 47.100.121.99
      port: 6379
      database: 15

   


server.port: 8081
